221 update disaster_identifier to array of Classification objects
GFDRR/rdl-standard pull request #232
Opened 2023-08-31 10:41 UTC by odscjen

**Related issues**

closes #221 
closes #142 

**Description**

**Merge checklist**

- [ ] Update the changelog ([style guide](developer_docs.md#changelog-style-guide))
- [ ] Run `./manage.py` pre-commit

If you added, removed or renamed a field:

- [ ] Update the `collapse` option of the jsonschema directives for dataset, resource, hazard, exposure, vulnerability and loss on `reference/schema.md`
- [ ] Update the diagrams in `reference/schema/md`

**Having trouble?**

See [how to resolve check failures](https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#resolve-check-failures).

2023-08-31 19:50 UTC, duncandewhurst requested changes

2023-08-31 19:50 UTC, duncandewhurst commented on schema/rdls_schema.json
> +          "description": "Disaster identifiers for this event.",
```suggestion
          "description": "Identifiers for the disaster to which this event relates.",
```

2023-08-31 22:59 UTC, duncandewhurst commented
The JSON files in `examples` also need to be updated.

2023-09-01 08:09 UTC, odscjen commented
None of the examples included this field so no updates needed there

2023-09-01 08:11 UTC, matamadio approved these changes

2023-09-01 08:35 UTC, merged