update docs/rdl/what - sentence addressing non-RDLS fields in datasets
GFDRR/rdl-standard pull request #234
Opened 2023-08-31 12:02 UTC by odscjen

**Related issues**

closes #56 

**Description**

**Merge checklist**

- [ ] Update the changelog ([style guide](developer_docs.md#changelog-style-guide))
- [ ] Run `./manage.py` pre-commit

If you added, removed or renamed a field:

- [ ] Update the `collapse` option of the jsonschema directives for dataset, resource, hazard, exposure, vulnerability and loss on `reference/schema.md`
- [ ] Update the diagrams in `reference/schema/md`

**Having trouble?**

See [how to resolve check failures](https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#resolve-check-failures).

2023-08-31 19:48 UTC, duncandewhurst commented
Is there also a need to list the individual fields somewhere? If so, I made a suggestion in https://github.com/GFDRR/rdl-standard/issues/149#issuecomment-1696324427

2023-08-31 19:48 UTC, duncandewhurst approved these changes

2023-09-08 10:25 UTC, matamadio requested changes
Edit:

> RDLS provides general guidance on how the risk datasets should be structured, but it does not have strict rules about which methods to apply or which fields or variables to include. The user ought to make sure that risk datasets follow a logical structure and include all the information necessary to fulfil their intended uses.

2023-09-11 10:24 UTC, odscjen commented
Noticed that this has been superceded by the conversation in #56 so I'm closing this and a new PR can be created once that discussion is concluded.

2023-09-11 10:24 UTC, closed without merging