Update IMT.csv
GFDRR/rdl-standard pull request #259
Opened 2023-09-26 14:49 UTC by matamadio

Add imt code for cyclone wind speed 10-min sustained. It was already there as km/h but STORM uses m/s...

This makes me reconsider the discussion in #5, and splitting IMT into two separate codelists:
- metric (optional)
- unit (mandatory)

So even if the specific metric (larger range of variability) is not in the codelist, one can still indicate the unit if part of the most common ones (smaller range of variability).

**Related issues**

**Description**

**Merge checklist**

If you added, removed or renamed a field:

- [ ] Update the `collapse` option of the jsonschema directives for dataset, resource, hazard, exposure, vulnerability and loss on `reference/schema.md`
- [ ] Update the diagrams in `reference/schema/md`
- [ ] Update the JSON files in `examples`

Always:

- [ ] Run `./manage.py` pre-commit
- [ ] Update the changelog ([style guide](developer_docs.md#changelog-style-guide))

**Having trouble?**

See [how to resolve check failures](https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#resolve-check-failures).

2023-09-26 15:12 UTC, matamadio commented
In addition: it's not always useful to specify the hazard type in the metric. In some cases it just create unnecessary duplication when the same metric:unit could be used.

E.g.
Why we need to differentiate FL from LS when speaking of flow depth, velocity?
How tsunami inundation depth is different from FL or LS "flow depth"?
Why we need to indicate "etc" (extra-tropical cyclones) for strong wind unit?

2023-10-09 15:45 UTC, odscjen requested changes

2023-10-09 15:45 UTC, odscjen commented on schema/codelists/open/IMT.csv
> +v_etc(10m):m/s,10-min sustained wind speed (mps),v_ect(10m),m/s,The average wind speed over a period of 10 minutes. Expressed in meters per second (mps).
```suggestion
v_etc(10m):m/s,10-min sustained wind speed in m/s,v_ect(10m),m/s,The average wind speed over a period of 10 minutes. Expressed in meters per second (m/s).
```

to match the other instances of meters per second

2023-10-09 15:47 UTC, odscjen commented
The other tests that are failing are because you've added some codes to closed codelists (metric_dimensions, and exposure_category) but you've not included the new codes in every instance of `enum` that uses that codelist.

2023-10-09 17:02 UTC, matamadio commented
> The other tests that are failing are because you've added some codes to closed codelists (metric_dimensions, and exposure_category) but you've not included the new codes in every instance of `enum` that uses that codelist. (this was presumably in a different PR)

I've only edited this open codelist. Anyway, I don't know how to do what you are suggesting: which file should be edited in addition to csvs?

2023-10-09 18:23 UTC, matamadio reviewed
Other lines have quotation marks as well.

2023-10-17 14:36 UTC, odscjen commented
Hi Mat you've got 3 errors showing up I'll deal with them in turn.

1. One or more codelist CSV files are invalid

The problem is that lines 11 and 12 in licence.csv both end with a space, they should just end with the comma. It looks like that error was introduced in this commit https://github.com/GFDRR/rdl-standard/commit/6e35b0b60afa9e8b918be1dc5e1ed27bf4ad577e

2. Files are not indented as expected

This one can be fixed by running `ocdskit indent -r .` as explained in the [developer docs](https://github.com/GFDRR/rdl-standard/blob/0.2-dev/developer_docs.md#test_jsonpytest_indent) You have to run this locally on your own computer, it can't be done within github.

3. One or more JSON Schema files are invalid

I've had a bit more of an investigate and the problem is again in an older commit to this base branch. It looks like Stu made a commit https://github.com/GFDRR/rdl-standard/commit/ba9472e7a9cd3c9baf80ff03cdf3d832b49b3f8b earlier that added 2 new codes to the exposure_category.csv. However he only updated the csv file itself. For closed codelists (like this one) the codes also need to match those in `enum` fields in the schema itself.

e.g.

```json
"category": {
          "title": "Asset category",
          "description": "The category of the lost assets, from the closed [exposure_category codelist](https://docs.riskdatalibrary.org/en/{{version}}/reference/codelists/#exposure-category).",
          "type": "string",
          "codelist": "exposure_category.csv",
          "openCodelist": false,
          "enum": [
            "agriculture",
            "buildings",
            "infrastructure",
            "population",
            "natural_environment"
          ]
        },
```
in this example (which is from `Losses`) only the original 5 codes are listed out but there's now 7 codes in the referenced file so the test expects to see those same 7 codes in the `enum` field where `codelist` references "exposure_category.csv".

2023-10-17 14:58 UTC, odscjen commented
> I see the change of removing quotation marks on line 7, but other lines have quotation marks as well..?

Ah yes you only need quotation marks if there are special characters (normally commas). If there aren't any, as is the case in that line of metric_dimensions.csv, the tests complain.

2023-10-30 15:40 UTC, matamadio commented
I think I solved some of the PR errors, but others remain:

- json indent (can't locate the issue, if exists)
- properties within properties (ignore?)

2023-10-30 15:54 UTC, odscjen commented
properties within properties can be safely ignored, it's just a warning rather than an actual error.

indent errors are almost impossible to spot by eye and requires the dev env to fix it using the ocdskit module. It's one of the tests that can be safely turned off for the time being if that's what you'd like?

2025-07-08 13:26 UTC, merged