Adding changelog
GFDRR/rdl-standard pull request #92
Opened 2023-06-14 13:35 UTC by odscrachel

Added a changelog file to docs/about

2023-06-14 22:39 UTC, duncandewhurst requested changes

2023-06-14 22:39 UTC, duncandewhurst commented on docs/about/changelog.md
> +
```suggestion

This page lists changes to the Risk Data Library Standard.

```

2023-06-14 22:39 UTC, duncandewhurst commented on docs/about/changelog.md
> +The Risk Data Library Standard adheres to [Semantic Versioning](https://semver.org/).
To my knowledge, semantic versioning isn't yet implemented so I suggest that we omit this for now.

```suggestion
```

2023-06-14 22:39 UTC, duncandewhurst commented on docs/about/changelog.md
> +
```suggestion
### Normative documentation

### Non-normative documentation

```

2023-06-14 22:46 UTC, duncandewhurst commented
@odscjen, since Rachel is on leave, I applied the suggestions from my review and resolved the check failure. Please could you review.

2023-06-19 08:53 UTC, odscjen submitted a review, later dismissed

2023-06-19 08:54 UTC, odscjen commented
passing back to you @duncandewhurst as it's still having merging blocked due to your requested changes (even though you've applied them)

2023-06-19 22:28 UTC, duncandewhurst approved these changes

2023-06-20 01:43 UTC, duncandewhurst commented
I realised that `changelog.md` was not listed in any toctree so I've added it under `about/history`. I've also configured ReadtheDocs to fail on warnings for missing references and documents that aren't included in any toctree. Those issues would have been caught by running `make autobuild` locally so it's good to have ReadtheDocs follow the same behaviour. I think this is now ready for review by @stufraser1 or @matamadio.

2023-06-20 12:05 UTC, stufraser1 approved these changes
I focussed on the structure of changelog, which looks good.

Note we've made lots of change to docs on branch docs.mat compared to dev - we obviously need to merge these changes with those.

2023-06-20 14:32 UTC, merged