Removing top level nesting
GFDRR/rdl-standard pull request #93
Opened 2023-06-14 13:52 UTC by odscrachel

Closes #57. Please note this is the first of many structural changes, so the json is still not valid

2023-06-14 13:54 UTC, odscrachel commented
Once #92 has been merged, need to update the changelog

2023-06-15 01:01 UTC, duncandewhurst requested changes

2023-06-15 01:01 UTC, duncandewhurst commented on schema/rdl_schema_0.1.json
> +	"resources": {
`resources` should be under `properties`.

2023-06-15 01:03 UTC, duncandewhurst commented on schema/rdl_schema_0.1.json
> +	"resources": {
Fixed in https://github.com/GFDRR/rdl-standard/pull/93/commits/60cd76ca7bc2205f3de29177d018ea9e4ca5580c

2023-06-15 01:05 UTC, duncandewhurst commented
@odscjen please can you review my changes in https://github.com/GFDRR/rdl-standard/pull/93/commits/60cd76ca7bc2205f3de29177d018ea9e4ca5580c?

2023-06-19 09:11 UTC, odscjen submitted a review, later dismissed
The nesting from the `common` object have all been removed, but the unnecessary top level nesting within the `vulnerability`, `loss` and `exposure` objects is still there. That'll be taken care of in a subsequent PR.

In terms of this PR removing unnecessary nesting in the top level object this can be approved.

2023-06-19 22:27 UTC, duncandewhurst submitted a review, later dismissed

2023-06-20 01:44 UTC, duncandewhurst commented
Let's wait for https://github.com/GFDRR/rdl-standard/pull/92 to be merged then we can merge `dev` into this branch and add a changelog entry before merging this PR.

2023-06-20 14:43 UTC, odscjen commented
merged in the changelog as Stu had approved, and updated to include a line about this change. No idea why checks are failing, error is 

"/home/runner/work/rdl-standard/rdl-standard/docs/about/history/changelog.md" is not formatted.

2023-06-20 23:23 UTC, duncandewhurst commented
How to resolve check failures is documented in https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#resolve-check-failures, specifically:

> #### mdformat
> 
> If this check fails, run the following command to fix markdown formatting:
> 
> ```bash
> mdformat docs
> ```

I've done that so the checks now pass.

2023-06-20 23:23 UTC, duncandewhurst approved these changes

2023-06-21 08:38 UTC, stufraser1 approved these changes

2023-06-22 03:39 UTC, merged